sudo: false
language: python
python:
  - "3.5"
dist: trusty
env:
  global:
    - PYTEST_ADDOPTS="-n 3"
  matrix:
    # TODO: py27
    # TODO: py34
    - TOX_ENV=py35-blockchain-fast
    - TOX_ENV=py35-blockchain-slow
    - TOX_ENV=py35-core
    - TOX_ENV=py35-state-fast
    - TOX_ENV=py35-state-slow
    - TOX_ENV=py35-transactions
    - TOX_ENV=py35-vm-fast
    - TOX_ENV=py35-vm-limits
    - TOX_ENV=py35-coincurve
    - TOX_ENV=py35-leveldb
    #- TOX_ENV=py35-vm-performance
    - TOX_ENV=flake8
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
